[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
prediction_market = "JDaQW4FeGSkt1QRcMfjoT2JxUR9WLD2Vg15Mx2yVWCwg"

[programs.localnet]
prediction_market = "JDaQW4FeGSkt1QRcMfjoT2JxUR9WLD2Vg15Mx2yVWCwg"


[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "node_modules/.bin/jest --preset ts-jest"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "127.0.0.1"
ledger = ".anchor/test-ledger"
rpc_port = 8899
